//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Future_Vet.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Data.Entity;

    public partial class AuditLog
    {
        [Key]
        public decimal AuditID { get; set; }
        public string UserName { get; set; }
        public string IPAddress { get; set; }
        public string AreaAccessed { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
        //Default Constructor
        public AuditLog() { }
    }
    //Example AuditingContext 
    public class AuditingContext : DbContext
    {
        public DbSet<AuditLog> AuditRecords { get; set; }
    }
}
