//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Future_Vet.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Future_VetEntities : DbContext
    {
        public Future_VetEntities()
            : base("name=Future_VetEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Animal_Breed> Animal_Breed { get; set; }
        public virtual DbSet<Animal_Type> Animal_Type { get; set; }
        public virtual DbSet<Invoice> Invoices { get; set; }
        public virtual DbSet<Log> Logs { get; set; }
        public virtual DbSet<Pet_Details> Pet_Details { get; set; }
        public virtual DbSet<Pet_Owner> Pet_Owner { get; set; }
        public virtual DbSet<Pet_Visit> Pet_Visit { get; set; }
        public virtual DbSet<Receipt> Receipts { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Vet> Vets { get; set; }
        public virtual DbSet<AuditLog> AuditLogs { get; set; }
    }
}
