//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Future_Vet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pet_Details
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pet_Details()
        {
            this.Pet_Visit = new HashSet<Pet_Visit>();
        }
    
        public decimal IDPet { get; set; }
        public string Pet_Name { get; set; }
        public Nullable<decimal> IDOwner { get; set; }
        public Nullable<decimal> IDBreed { get; set; }
        public Nullable<System.DateTime> Birthdate { get; set; }
        public Nullable<decimal> IDAnimal_Type { get; set; }
        public string TagNumber { get; set; }
    
        public virtual Animal_Breed Animal_Breed { get; set; }
        public virtual Animal_Type Animal_Type { get; set; }
        public virtual Pet_Owner Pet_Owner { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pet_Visit> Pet_Visit { get; set; }
    }
}
