//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Future_Vet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Receipt
    {
        public decimal IDReceipt { get; set; }
        public Nullable<System.DateTime> ReceiptDate { get; set; }
        public Nullable<decimal> ReceiptAmount { get; set; }
        public Nullable<System.DateTime> CaptureDate { get; set; }
        public Nullable<decimal> IDInvoice { get; set; }
    
        public virtual Invoice Invoice { get; set; }
    }
}
